#!/usr/bin/env python

import sys
from subprocess import check_output, check_call

whitelist = set(sys.argv[1:])
all_files = set(check_output(['git', 'ls-files']).decode('utf8').splitlines())
to_rm = all_files.difference(whitelist)
if to_rm:
    out = check_output(['git', 'rm', '--cache'] + list(to_rm)).decode('utf8').splitlines()
    print("Removed %i files" % len(out))
    
    

